package org.jkm.springintegration.datatransfer.component;

import org.springframework.integration.annotation.Gateway;
import org.springframework.integration.annotation.MessagingGateway;

/**
 * Input gateway required to connect to the data transfer flow.
 *
 * <p>The implementation is autogenerated by the spring integration framework.
 */
@MessagingGateway
public interface InputMessagingGateway {
  /**
   * Starts the integration flow for twitter query.
   *
   * @param query twitter query.
   * @return String
   */
  @Gateway(requestChannel = "database.channel")
  String invokeDatabase(String query);
}
